### PR TITLE
Use pretty (#-less) urls

### PR DESCRIPTION
**Pull request by ramnivas**
I am not sure what is your preference related to "pretty urls" (no '#'), but here is a PR to implement it!

### CODE REVIEW

**Comment by ochrons** [comment]
But does this work with the Workbench approach, when not using the server? Main reason for using # for the tutorial was to make it work in both cases.

**Comment by ramnivas** [comment]
Is `http://localhost:13131/jvm/target/scala-2.11/classes/web/index.html` the right url to work with the Workbench? When I tried that, I could see the the app, but the TODO page didn't work (it made the Ajax call to `http://localhost:13131/api/spatutorial/shared/Api/getTodos`, which failed) leading to a blank page.

**Comment by ochrons** [comment]
Yes. The ajax stuff naturally doesn't work in Workbench, but the client rendering and navigation does. So if you just want to develop a new component or try out different CSS styles, it's a bit more convenient than going through the server.

**Comment by ramnivas** [comment]
I guess that makes Workbench not very suitable for this particular project (as opposed to for projects creating standalone components). How about defining "apiRoot" so that the the api uri is independent of the browser uri? I guess that might bring in CORS issues.

Somewhat related. In my current project (still in infancy), I ended up separating the server and the client. The client is served through node/express (just serving static files). I found that dealing with CORS is easier than figuring out a cleaner solution for JVM+(Scala)JS development in the same project :-) For development, I use gulp to implement asset compilation (SASS, minification, etc.). I use browsersync to automatically update browser instead of Workbench. browsersync works quite well (in fact, it does a really nice job when it comes to modifying just CSS).

Shall we close this PR? In any case, I think it will be nice to have the README mention the uri to work with Workbench and its limitations.

**Comment by ochrons** [comment]
I actually already updated the documentation (and source code) in the latest release to point out why the # is used :)

This project is more like a "bag of tricks" to provide a good platform for experimenting with different things. That's why I'm not too concerned about the Ajax stuff not working in Workbench. You can still do a lot of experimenting without it.

**Comment by ramnivas** [comment]
I saw that you added the reasoning behind using #. What I meant was to add the URI needed to use the Workbench feature. So made PR #3. It will be still nice to add its limitation to make sure a new person isn't surprised.

**Pull request closed without merging**
