### PR TITLE
cdn and asset versioning

### PR DESCRIPTION
**Pull request by Enalmada**
Add cdn and asset versioning to the tutorial so new users have more examples of spa best practices out of the box.

### CODE REVIEW

**Comment by ochrons** [comment]
Looks nice, thanks! Can you also add a bit to the tutorial documentation to shortly describe what's going on an link to the appropriate section in Play's documentation?

**Comment by Enalmada** [comment]
Good idea!  Ok, I added documentation which hopefully makes sense.

**Comment by Enalmada** [comment]
asset backticks added.  If you have anything you prefer changed let me know!

**Comment by ochrons** [comment]
LGTM!

**Pull request merged**
